### PR TITLE
Using dbus and Gio

### PR DESCRIPTION
**Pull request by brunelli**
Hello!

I changed the script a little bit for it to use dbus (in replace of subprocess and notify-send) and Gio (in replace of mimetypes, subprocess and xdg-open).

Please test it and tell if something is not of your taste.

Cheers, Ian.

### CODE REVIEW

**Comment by flavioelawi** [comment]
hey Ian!
I like the dbus approach!
but can we make it without the popup windows? I think that something that imitates the notify-send behavior would be better!

**Comment by brunelli** [comment]
I'm sorry, what popup windows are you referring to?

**Comment by flavioelawi** [comment]
image

I am on Unity and uploading a file throw this

**Comment by brunelli** [comment]
Oh... This doesn't happen in GNOME Shell. I'll do some research later.

**Comment by brunelli** [comment]
I don't have Unity, so... Can you confirm that the following code display the notification AND a window?

```
#!/bin/env python2
import dbus

summary = "Lorem ipsum"
body = "Dolor sit amet"
app_name = ""
app_icon = "terminal"
timeout = 5000
actions = []
hints = []
replaces_id = 0

_bus_name = "org.freedesktop.Notifications"
_object_path = "/org/freedesktop/Notifications"
_interface_name = _bus_name

session_bus = dbus.SessionBus()
obj = session_bus.get_object(_bus_name, _object_path)
interface = dbus.Interface(obj, _interface_name)
interface.Notify(app_name, replaces_id, app_icon,
                 summary, body, actions, hints, timeout)
```

**Comment by flavioelawi** [comment]
this displays only the notification, no window.

**Comment by brunelli** [comment]
So, it was probably because of the timeout...

Can you replace the last `0` in:

```
interface.Notify("Nautilus", 0, "nautilus",
                         "Upload done",
                         "Your file %s was uploaded" % file.get_name(),
                         [], [], 0)
```

to `5000` and tell me if it does the tricky?

**Comment by flavioelawi** [comment]
yes, you were right, now it correctly displays the notification :)

**Pull request merged**
